// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DynamicRowHeightDemo
{
	public partial class DynamicCell : UITableViewCell
	{
		public DynamicCell (IntPtr handle) : base (handle)
		{
		}

        public void SetTitle(string title)
        {
            TitleLabel.Text = title;
        }

        public void SetText(string text)
        {
            TextLabel.Text = text;
        }
	}
}
